### ISSUE TITLE
HAproxy 2.4 cannot bind socket (Permission denied) [0.0.0.0:80]

### ISSUE THREAD

**Issue by craph** [docker-library/haproxy#170] opened 2021-09-16 10:26 UTC
Hello,

I opened this issue : https://github.com/haproxy/haproxy/issues/1394

I don't know if I opened it in the right place.

Best regards,

**Comment by TimWolla** [comment] 2021-09-16 10:31
Duplicate of #160

**Comment by craph** [comment] 2021-09-16 11:25
where is the check for the privileged port ? I don't understand the reason of the changes

**Comment by craph** [comment] 2021-09-16 12:16
@TimWolla  If I check the Dockerfile in : https://github.com/docker-library/haproxy/blob/e01e11b9df6dce3498f0d58f4bb5d0e5f6cd8715/2.4/Dockerfile and the one here : https://github.com/haproxytech/haproxy-docker-alpine/blob/main/2.4/Dockerfile  why they are not the same ? 

I was thinking the official image in dockerhub was the same as the image in the repo of haproxy

**Comment by stevenmasci** [comment] 2021-11-14 07:10
My docker host machine is running CentOS 7 so `-sysctl net.ipv4.ip_unprivileged_port_start=0` didn't work for me. Kernel version too low.

But using the capabilities system and CAP_NET_BIND_SERVICE capability works! Here's my dockerfile.

```Dockerfile
FROM haproxy:2.4

USER root

RUN apt-get update
RUN apt-get install libcap2-bin -y
RUN setcap 'cap_net_bind_service=+ep' /usr/local/sbin/haproxy

USER haproxy

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
```

**Closed** 2022-06-11 00:12 UTC
Labels: question

**Comment by Shardj** [comment] 2023-01-25 11:50
You're a lifesaver @stevenmasci 

I'm using ubuntu 20 but I was getting "Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: sysctl "net.ipv4.ip_unprivileged_port_start" not allowed in host network namespace: unknown"

Your solution works perfectly though!

**Comment by jcmoraisjr** [comment] 2024-03-17 16:36
> `RUN setcap 'cap_net_bind_service=+ep' /usr/local/sbin/haproxy`

Hey folks, as far as I can tell, the haproxy bin doesn't have the NET_BIND_SERVICE capability added by default in the haproxy container image. Is there a reason for that, e.g. some security concern or it is not guaranteed to work on all scenarios?

**Comment by tianon** [comment] 2024-03-18 22:58
Setting the capability in the image relies on consistent handling of xattrs, which is not something we can guarantee (even for the systems which build the images).

The best "fix" here is a newer kernel that supports `ip_unprivileged_port_start` and either setting that explicitly on your container or upgrading Docker to a version that sets it automatically for you (which even as old as 20.10 does).

See also https://github.com/moby/moby/issues/8460, https://github.com/moby/moby/pull/41030, https://github.com/moby/moby/commit/888da28d42f7d0f9fa250dd8a75d51c2a6cf3098.

**Comment by jcmoraisjr** [comment] 2024-03-20 01:14
Thanks for the clarification and links, really appreciated! Let me summarize the options to bind 80/443 and their problems in order to see if I understood them correctly, or if I'm missing any other option:

* Add `NET_BIND_SERVICE` capability in the haproxy bin - it uses extended attributes which is not supported on all container runtime deployments, maybe even in the build environment;
* Define `ip_unprivileged_port_start` Kernel param as `0` - it does not work if using the host network; needs Kernel 4.11 or newer;
* Bind on unprivileged ports and link them externally on 80/443 - it does not work if using the host network;
* Use a container runtime that configures `ip_unprivileged_port_start` as `0` by default;
* Run the container as root.

My use case is running haproxy embedded on a network component, and the way the user deploys it vary. I'm planning to add a few words in the documentation that clarifies their options and what might not work as expected.
