### ISSUE TITLE
Dir/user permissions in haproxy version 2.4

### ISSUE THREAD

**Issue by saso5** [docker-library/haproxy#158] opened 2021-05-20 11:00 UTC
Upgrading to haproxy 2.4 my config doesn't work anymore because of changes in dir/user permissions for `stats socket` config.  

Error can be reproduced by using your example:  
http://git.haproxy.org/?p=haproxy-2.4.git;a=blob;f=examples/content-sw-sample.cfg;h=e54f9760edacaa1eeff397093a0b72a74ac30309;hb=HEAD

```
loadbalancer     | [NOTICE]   (1) : haproxy version is 2.4.0-6cbbecf                                                                                                                                                                   loadbalancer     | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy                                                                                                                                                      loadbalancer     | [ALERT]    (1) : Starting frontend GLOBAL: cannot bind UNIX socket (Permission denied) [/var/run/haproxy.stat]                                                                                                      loadbalancer     | [ALERT]    (1) : [haproxy.main()] Some protocols failed to start their listeners! Exiting.
```

Known workaround:   

Add `USER root` command to local Dockerfile

**Comment by wglambert** [comment] 2021-05-20 16:47
I can reproduce when running as non-root 

`haproxy:latest`
```console
$ docker run -d --name haproxy haproxy:test
67afc9def70ac4adcc373eb49877888dfdef0032d0ae5e8f8413482f1ab073ea

$ docker logs haproxy
[NOTICE]   (1) : haproxy version is 2.4.0-6cbbecf
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (1) : Starting frontend GLOBAL: cannot bind UNIX socket (Permission denied) [/var/run/haproxy.stat]
[ALERT]    (1) : [haproxy.main()] Some protocols failed to start their listeners! Exiting.
```

`haproxy:2.3` (noisy from improper config but works)
```console
$ docker run -d --name haproxy haproxy:test
50c50de1e3f5926ffe3a94529cf75d1c7603c41721630cfb2a3fc9b0641916aa

$ docker logs haproxy
[NOTICE] 139/164133 (1) : New worker #1 (9) forked
[WARNING] 139/164134 (9) : Server static/statsrv1 is DOWN, reason: Layer4 timeout, check duration: 1001ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 139/164134 (9) : Server static/statsrv2 is DOWN, reason: Layer4 timeout, check duration: 1001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[NOTICE] 139/164134 (9) : haproxy version is 2.3.10-4764f0e
[NOTICE] 139/164134 (9) : path to executable is /usr/local/sbin/haproxy
[ALERT] 139/164134 (9) : backend 'static' has no server available!
[WARNING] 139/164134 (9) : Server dynamic/dynsrv1 is DOWN, reason: Layer4 timeout, check duration: 1001ms. 3 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 139/164134 (9) : Server dynamic/dynsrv2 is DOWN, reason: Layer4 timeout, check duration: 1000ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 139/164134 (9) : Server dynamic/dynsrv3 is DOWN, reason: Layer4 timeout, check duration: 1002ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 139/164135 (9) : Server dynamic/dynsrv4 is DOWN, reason: Layer4 timeout, check duration: 1001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT] 139/164135 (9) : backend 'dynamic' has no server available!
```

The config I used (removed set uid/gid, and chroot so it runs as default haproxy user UID 99)
<details>
<summary> haproxy.cfg </summary>

```cfg
global
        maxconn         10000
        stats socket    /var/run/haproxy.stat mode 600 level admin
        log             127.0.0.1 local0
        daemon

# The public 'www' address in the DMZ
frontend public
        bind            127.0.0.1:8080 name clear
        #bind            192.168.1.10:443 ssl crt /etc/haproxy/haproxy.pem
        mode            http
        log             global
        option          httplog
        option          dontlognull
        monitor-uri     /monitoruri
        maxconn         8000
        timeout client  30s

        stats uri       /admin/stats
        use_backend     static if { hdr_beg(host) -i img }
        use_backend     static if { path_beg /img /css   }
        default_backend dynamic

# The static backend backend for 'Host: img', /img and /css.
backend static
        mode            http
        balance         roundrobin
        option prefer-last-server
        retries         2
        option redispatch
        timeout connect 5s
        timeout server  5s
        option httpchk  HEAD /favicon.ico
        server          statsrv1 192.168.1.8:80 check inter 1000
        server          statsrv2 192.168.1.9:80 check inter 1000

# the application servers go here
backend dynamic
        mode            http
        balance         roundrobin
        retries         2
        option redispatch
        timeout connect 5s
        timeout server  30s
        timeout queue   30s
        option httpchk  HEAD /login.php
        cookie          DYNSRV insert indirect nocache
        fullconn        4000 # the servers will be used at full load above this number of connections
        server          dynsrv1 192.168.1.1:80 minconn 50 maxconn 500 cookie s1 check inter 1000
        server          dynsrv2 192.168.1.2:80 minconn 50 maxconn 500 cookie s2 check inter 1000
        server          dynsrv3 192.168.1.3:80 minconn 50 maxconn 500 cookie s3 check inter 1000
        server          dynsrv4 192.168.1.4:80 minconn 50 maxconn 500 cookie s4 check inter 1000
```

</details>

**Comment by akerr-CINC** [comment] 2021-06-08 16:55
I linked this to the port mapping issue that I created, which I solved by changing my container to use non-privileged ports and just mapping them to privileged ports on the host.  I also had permissions problem with writing the pidfile.

I'm not sure this is a bug... but its certainly a "gotcha" that wasn't expected and has a high probability of impacting anyone using the "latest" tag (which isn't a good practice).

**Comment by shadow7412** [comment] 2021-06-22 02:07
This change also impacts dockerfiles that rely on the haproxy image. For example, I use apt-get to install dependencies required to run authelia.

I've just added `USER root` for now.

**Comment by yosifkit** [comment] 2021-06-22 23:01
The user change is noted on the Docker Hub page ([src](https://github.com/docker-library/docs/blob/aabad9a5d97dae6d62568f602bb069a88bee46cb/haproxy/README.md#run-the-container) quoted below). If you have suggestions PRs are welcome to improve the documentation.

> You will need a kernel at [version 4.11 or newer](https://github.com/moby/moby/issues/8460#issuecomment-312459310) to use `--sysctl net.ipv4.ip_unprivileged_port_start=0` , you may need to publish the ports your HAProxy is listening on to the host by specifying the -p option, for example -p 8080:80 to publish port 8080 from the container host to port 80 in the container. Make sure the port you're using is free.
>
>**Note:** the 2.4+ versions of the container will run as `USER haproxy` by default (hence the `--sysctl net.ipv4.ip_unprivileged_port_start=0` above), but older versions still default to `root` for compatibility reasons; use `--user haproxy` (or any other UID) if you want to run as non-root in older versions.


The `2.4` and above images run as the `haproxy` user by default. So if the user-supplied config file specifies other directories or files that haproxy needs access to (like `stats socket /var/run/haproxy.stat [...]`), then the user will need to ensure that those directories exist with the proper permissions (e.g. an image `FROM haproxy:2.4` that creates the needed directories, or a `docker volume` with the correct permissions).

**Comment by lvillis** [comment] 2021-07-04 10:30
Add "--sysctl net.ipv4.ip_unprivileged_port_start=0" to the docker run command to solve the problem perfectly.

`$ docker run -d --name haproxy --sysctl net.ipv4.ip_unprivileged_port_start=0 haproxy:latest`

**Comment by tianon** [comment] 2021-08-24 23:32
Closing, since this is by design.

It's also useful to note that the `net.ipv4.ip_unprivileged_port_start` sysctl is set by default in Docker 20.10+ (via https://github.com/moby/moby/pull/41030).

**Closed by tianon** 2021-08-24 23:32 UTC
Labels: Issue
