### ISSUE TITLE
`haproxy:2.9-alpine` missing from Docker Hub

### ISSUE THREAD

**Issue by legobeat** [docker-library/haproxy#240] opened 2024-12-14 02:09 UTC
The following tags are advertised as available on [Docker Hub](https://hub.docker.com/_/haproxy) but are not available on the registry:

- `haproxy:2.9.13-alpine`
- `haproxy:2.9-alpine`
- `haproxy:2.9.13-alpine3.21`
- `haproxy:2.9-alpine3.21`

These unadvertised older tags are still available:

- `haproxy:2.9.13-alpine3.20`
- `haproxy:2.9-alpine3.20`

**Comment by beatkind** [comment] 2024-12-14 08:43
It is not only the 2.9 images also the 3.0 images. Same fix applies to them.

**Comment by johnjeffers** [comment] 2024-12-14 11:13
I'd like to add that this is causing production problems, so a rapid fix would be greatly appreciated!

It seems that any haproxy image whose tag contains `alpine` is failing. Worse, since the metadata was published to Docker Hub, our image cache isn't saving us because it sees that there is new metadata for the image, but it's unable to pull it.

**Comment by thaJeztah** [comment] 2024-12-14 17:15
This looks to be the same cause as the ticket below (for another repository); the team is actively working on this;


- https://github.com/docker-library/docker/issues/519

**Comment by LaurentGoderre** [comment] 2024-12-14 17:59
Closing in favor of the issuer mentioned above.

**Closed by LaurentGoderre** 2024-12-14 17:59 UTC

**Comment by thaJeztah** [comment] 2024-12-14 19:17
Update on this issue; a colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"

There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images. These images will likely be processed later, which may be done after the weekend.
